repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: trailing-whitespace
- repo: local
  hooks:
    - id: flutter-fix
      name: fix common linting rules
      entry: fvm dart fix --apply
      language: system
      files: lib/*
# - repo: https://github.com/Cretezy/flutter-format-pre-commit
#   rev: master
#   hooks:
#   - id: flutter-format
#     files: lib/*
#     exclude: lib/src/utils.dart
#     args: [--line-length=150]
# - repo: https://github.com/dluksza/flutter-analyze-pre-commit
#   rev: "master"
#   hooks:
#     - id: flutter-analyze
#       args: [lib/*]
