repos:
- repo: local
  hooks:
    - id: flutter-fix
      name: fix common linting rules
      # entry: .fvm/flutter_sdk/bin/dart fix --apply
      # language: dart
      entry: bash
      language: system
      args: ['-c', '.fvm/flutter_sdk/bin/dart fix --apply']
      files: lib/*
- repo: local
  hooks:
    - id: flutter-analyze
      name: run flutter analyze
      entry: bash
      language: system
      args: ['-c', '.fvm/flutter_sdk/bin/flutter analyze']
      files: lib/*

