include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    avoid_dynamic_calls: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    use_key_in_widget_constructors: false
    sort_child_properties_last: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    avoid_void_async: true
    unnecessary_parenthesis: true
    always_declare_return_types: true
    unawaited_futures: true
    only_throw_errors: true
    missing_whitespace_between_adjacent_strings: true
    require_trailing_commas: true
    lines_longer_than_80_chars: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
