name: username_creation_feature
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ^3.7.3

dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: 5.4.1
  flutter_bloc: 8.1.3
  freezed_annotation: 2.4.1
  coreui:
    path: ../../Shared/coreui
  di:
    path: ../../Shared/di
  validators:
    path: ../../Shared/validators
  users_use_cases:
    path: ../../UseCases/users_use_cases
  shared_states:
    path: ../../Shared/shared_states

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: 2.1.0
  build_runner: 2.2.1

flutter:
