name: login_feature
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ^3.7.3

dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: 5.4.1
  flutter_bloc: 8.1.3
  freezed_annotation: 2.4.1
  coreui:
    path: ../../Shared/coreui
  auth_use_cases:
    path: ../../UseCases/auth_use_cases
  local_storage_use_cases:
    path: ../../UseCases/local_storage_use_cases
  di:
    path: ../../Shared/di
  shared_states:
    path: ../../Shared/shared_states
  shared_models:
    path: ../../Shared/shared_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.2.1
  freezed: 2.1.0

flutter:
