name: auth_use_cases
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ^3.7.3

dependencies:
  flutter:
    sdk: flutter
  injectable: 2.1.2
  get_it: 7.6.0
  network:
    path: ../../Shared/network
  di:
    path: ../../Shared/di
  shared_models:
    path: ../../Shared/shared_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.2.1
  flutter_lints: ^2.0.0
  injectable_generator: 2.1.4

flutter:
