name: local_storage_use_cases
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ^3.7.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 2.2.0
  injectable: 2.1.2
  get_it: 7.6.0
  di:
    path: ../../Shared/di
  local_storage:
    path: ../../Shared/local_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: 2.1.4
  build_runner: 2.2.1

flutter:
