name: router
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ^3.7.3

dependencies:
  flutter:
    sdk: flutter
  login_feature:
    path: ../../Features/login_feature
  home_feature:
    path: ../../Features/home_feature
  profile_feature:
    path: ../../Features/profile_feature
  username_creation_feature:
    path: ../../Features/username_creation_feature

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
