name: router
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ^3.7.3

dependencies:
  flutter:
    sdk: flutter
  login_feature:
    path: ../../Features/login_feature
  home_feature:
    path: ../../Features/home_feature
  profile_feature:
    path: ../../Features/profile_feature
  username_creation_feature:
    path: ../../Features/username_creation_feature
  restricted_login_flow:
    path: ../../Features/restricted_login_flow
  paymaya_dev_login:
    path: ../../Features/dev_login

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  # freezed_annotation: 2.4.1
  flutter_keyboard_visibility: 5.4.0
  injectable:  2.1.2
  shared_preferences: 2.2.0
  dio: 5.3.2

flutter:
