name: saving_app
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ^3.7.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  router:
    path: ../../coordinator/router
  shared_states:
    path: ../../Shared/shared_states
  coreui:
    path: ../../Shared/coreui
  di:
    path: ../../Shared/di

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
