name: validators
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ^3.7.3

dependencies:
  flutter:
    sdk: flutter
  dartz: 0.10.1
  freezed_annotation: 2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: 2.1.0
  build_runner: 2.2.1

flutter:
