name: local_storage
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ^3.7.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
